sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 90327
  alioss:
    bucket-name: medeah-sky-take-out
    endpoint: oss-cn-beijing.aliyuncs.com
  spring:
    redis:
      password: 123456
      port: 6379
      host: localhost
      database: 0
